version: "3.7"

services:
  php7-fpm:
    container_name: php73-fpm-project13
    image: my-images/php73-fpm-alpine:0.1
    restart: always
    volumes:
      - /home/docker/projects/13_blog_laravel8:/usr/share/nginx/html
    networks:
      - backEnd-network

  nginx:
    container_name: nginx-project13
    env_file: .env
    image: my-images/nginx117-alpine:0.1
    volumes:
      - /home/docker/projects/13_blog_laravel8:/usr/share/nginx/html
    ports:
      - 8908:${PORT}
    networks:
      - backEnd-network
    links:
      - php7-fpm

  postgresql:
    container_name: postgresql-project13
    image: my-images/postgresql12-alpine:0.1
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
        - ${POSTGRES_PORT}:5432
    networks:
        - backEnd-network

  # mysql:
  #   container_name: mysql-project13
  #   image: my-images/mysql57-debian:0.1
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   volumes:
  #     - pgdata-blog:/var/lib/mysql
  #   ports:
  #     - ${MYSQL_PORT}:3306
  #   networks:
  #     - backEnd-network

networks:
  backEnd-network:
    driver: bridge

volumes:
  pgdata:
    name: "pgdata_13_blog_laravel8" ## cambiar por pgdata_<nombre-carpeta-proyecto>
    external: false
